### ISSUE TITLE
The request header could be configurable, or used any standart

### ISSUE THREAD

**Issue by edgardleal** [almerindo/traceability#2]
https://github.com/almerindo/traceability/blob/59f7f485a979e4657a0eb454e83fffd99e75aa47/src/ContextAsyncHooks.ts#L37

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields ( see `X-Request-ID` section ).

> PS: it is not a standard, but is commonly used by others libraries.

**Comment by almerindo** [comment]
Please, take a look on https://github.com/almerindo/traceability/pull/4.

We will let the trackId name too  for compatibility questions.
