### ISSUE TITLE
How can write log default in console

### ISSUE THREAD

**Issue by bdviett** [almerindo/traceability#33]
Hi guy, I want get cid in console on default (run application). How can I config it. Thanks.

**Comment by almerindo** [comment]
I'm Sorry!! 
I didn't see your comment!

I believe that you can follow the steps described in the Readme file.

Here is an example:

```
import {ContextAsyncHooks, Logger} from 'traceability'

const levelRoot = () =>{
  const {cid} = ContextAsyncHooks.getTrackId({})
  ContextAsyncHooks.setContext({cid})
  Logger.info('levelRoot');
  level1()

}
const level1 =  () =>{
  Logger.info('level1');
  level2();
}

const level2 =  () =>{
  Logger.info('level2');
}

levelRoot();
```

The Logger will show the CID in console as default.
